// ============================================================
// Blueprint Pack Export — JSON, Markdown, HTML exports
// ============================================================

import type { BlueprintPack, BlueprintSheet } from './blueprintSheetTypes';

// ---- JSON Export ----
export function exportBlueprintPackJson(pack: BlueprintPack): string {
  return JSON.stringify(pack, null, 2);
}

// ---- Markdown Export ----
export function exportBlueprintPackMarkdown(pack: BlueprintPack): string {
  const lines: string[] = [];
  lines.push(`# Blueprint Pack — ${pack.projectName}`);
  lines.push(`**Generated:** ${new Date(pack.generatedAt).toLocaleString()}`);
  lines.push(`**Revision:** ${pack.revision}`);
  lines.push(`**Status:** ${pack.status}`);
  lines.push(`**Template:** ${pack.templateName || "Custom"}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Summary
  lines.push("## Pack Summary");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Sheets | ${pack.summary.totalSheets} |`);
  lines.push(`| Generated | ${pack.summary.generatedSheets} |`);
  lines.push(`| Missing Data | ${pack.summary.missingDataSheets} |`);
  lines.push(`| Warnings | ${pack.summary.warnings} |`);
  lines.push(`| Errors | ${pack.summary.errors} |`);
  lines.push(`| Blockers | ${pack.summary.blockers} |`);
  lines.push("");

  // Each sheet
  pack.sheets.forEach((sheet) => {
    lines.push("---");
    lines.push("");
    lines.push(`## Sheet ${sheet.sheetNo}: ${sheet.title}`);
    lines.push(`**Category:** ${sheet.category} | **Status:** ${sheet.status}`);
    lines.push("");

    // Notes
    if (sheet.notes.length > 0) {
      lines.push("### Notes");
      sheet.notes.forEach(n => lines.push(`- ${n}`));
      lines.push("");
    }

    // Tables
    sheet.tables.forEach(table => {
      lines.push(`### ${table.title}`);
      if (table.columns.length > 0) {
        lines.push(`| ${table.columns.join(" | ")} |`);
        lines.push(`| ${table.columns.map(() => "---").join(" | ")} |`);
        table.rows.forEach(row => {
          lines.push(`| ${row.join(" | ")} |`);
        });
      }
      lines.push("");
    });

    // Warnings
    if (sheet.warnings.length > 0) {
      lines.push("### Warnings");
      sheet.warnings.forEach(w => lines.push(`- **[${w.severity}]** ${w.title}: ${w.message}`));
      lines.push("");
    }

    // Disclaimer
    if (sheet.disclaimer) {
      lines.push(`> ⚠️ ${sheet.disclaimer}`);
      lines.push("");
    }

    // Source references
    if (sheet.sourceObjects.length > 0) {
      lines.push(`*Sources: ${sheet.sourceObjects.map(s => s.label || s.id).join(", ")}*`);
      lines.push("");
    }

    // Drawing summary
    const d = sheet.drawing;
    if (d.objects.length > 0) {
      lines.push(`*Drawing: ${d.objects.length} objects, ${d.connections.length} connections, ${d.dimensions.length} dimensions*`);
      lines.push("");
    }
  });

  lines.push("---");
  lines.push(`*Generated by Hardware Studio — ${new Date(pack.generatedAt).toISOString()}*`);
  return lines.join("\n");
}

// ---- HTML Export ----
function renderSheetHtml(sheet: BlueprintSheet): string {
  const statusClass = sheet.status === "Generated In App" ? "status-generated" :
    sheet.status === "Missing Data" ? "status-missing" :
    sheet.status === "Draft" ? "status-draft" : "status-review";

  let html = `<div class="sheet-page">`;
  
  // Title block
  html += `<div class="title-block">`;
  html += `<div class="title-row"><span class="sheet-no">Sheet ${sheet.sheetNo}</span><h2>${sheet.title}</h2><span class="status-badge ${statusClass}">${sheet.status}</span></div>`;
  html += `<div class="meta-row"><span>Category: ${sheet.category}</span></div>`;
  html += `</div>`;

  // Drawing summary
  const d = sheet.drawing;
  if (d.objects.length > 0) {
    html += `<div class="drawing-info"><em>${d.objects.length} drawing objects, ${d.connections.length} connections</em></div>`;
  }

  // Notes
  if (sheet.notes.length > 0) {
    html += `<div class="notes"><h3>Notes</h3><ul>`;
    sheet.notes.forEach(n => { html += `<li>${n}</li>`; });
    html += `</ul></div>`;
  }

  // Tables
  sheet.tables.forEach(table => {
    html += `<div class="table-section"><h3>${table.title}</h3><table><thead><tr>`;
    table.columns.forEach(c => { html += `<th>${c}</th>`; });
    html += `</tr></thead><tbody>`;
    table.rows.forEach(row => {
      html += `<tr>`;
      row.forEach(cell => { html += `<td>${cell}</td>`; });
      html += `</tr>`;
    });
    html += `</tbody></table></div>`;
  });

  // Warnings
  if (sheet.warnings.length > 0) {
    html += `<div class="warnings"><h3>Warnings</h3><ul>`;
    sheet.warnings.forEach(w => {
      const cls = w.severity === "Blocker" ? "blocker" : w.severity === "Error" ? "error" : w.severity === "Warning" ? "warning" : "info";
      html += `<li class="${cls}"><strong>[${w.severity}]</strong> ${w.title}: ${w.message}</li>`;
    });
    html += `</ul></div>`;
  }

  // Disclaimer
  if (sheet.disclaimer) {
    html += `<div class="disclaimer">⚠️ ${sheet.disclaimer}</div>`;
  }

  html += `</div><!-- end sheet-page -->`;
  return html;
}

export function exportBlueprintPackHtml(pack: BlueprintPack): string {
  let html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Blueprint Pack — ${pack.projectName}</title>`;
  html += `<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #fff; color: #1e293b; font-size: 11px; line-height: 1.5; }
    .cover { padding: 40px; text-align: center; page-break-after: always; }
    .cover h1 { font-size: 28px; font-weight: 900; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 1px; }
    .cover .meta { font-size: 12px; color: #64748b; margin: 4px 0; }
    .cover .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; max-width: 500px; margin: 24px auto; text-align: center; }
    .cover .summary-item { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; }
    .cover .summary-item .val { font-size: 22px; font-weight: 800; }
    .cover .summary-item .lbl { font-size: 9px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; }
    .sheet-page { padding: 24px 32px; page-break-after: always; }
    .title-block { border-bottom: 2px solid #0f172a; padding-bottom: 8px; margin-bottom: 16px; }
    .title-row { display: flex; align-items: center; gap: 12px; }
    .sheet-no { font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; color: #64748b; min-width: 70px; }
    .title-row h2 { font-size: 16px; font-weight: 800; flex: 1; }
    .status-badge { font-size: 9px; font-weight: 700; padding: 2px 8px; border-radius: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
    .status-generated { background: #dcfce7; color: #166534; }
    .status-missing { background: #fef2f2; color: #991b1b; }
    .status-draft { background: #fefce8; color: #854d0e; }
    .status-review { background: #eff6ff; color: #1e40af; }
    .meta-row { font-size: 10px; color: #64748b; margin-top: 4px; }
    .drawing-info { font-size: 10px; color: #94a3b8; margin-bottom: 12px; }
    h3 { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; margin: 12px 0 6px; color: #334155; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 12px; font-size: 10px; }
    th { background: #f1f5f9; border: 1px solid #e2e8f0; padding: 4px 6px; text-align: left; font-weight: 700; text-transform: uppercase; font-size: 9px; letter-spacing: 0.3px; }
    td { border: 1px solid #e2e8f0; padding: 3px 6px; }
    .notes ul, .warnings ul { padding-left: 16px; margin-bottom: 8px; }
    .notes li, .warnings li { margin-bottom: 2px; }
    .warnings .blocker { color: #991b1b; font-weight: 600; }
    .warnings .error { color: #dc2626; }
    .warnings .warning { color: #d97706; }
    .warnings .info { color: #2563eb; }
    .disclaimer { background: #fefce8; border: 1px solid #fde68a; border-radius: 4px; padding: 6px 10px; font-size: 10px; color: #854d0e; margin-top: 12px; }
    @media print { .sheet-page { page-break-after: always; } }
  </style></head><body>`;

  // Cover page
  html += `<div class="cover">`;
  html += `<h1>${pack.projectName}</h1>`;
  html += `<p class="meta">Blueprint Pack — ${pack.templateName || "Custom Template"}</p>`;
  html += `<p class="meta">Revision ${pack.revision} | Generated ${new Date(pack.generatedAt).toLocaleString()}</p>`;
  html += `<p class="meta">Status: <strong>${pack.status}</strong></p>`;
  html += `<div class="summary-grid">`;
  html += `<div class="summary-item"><div class="val">${pack.summary.totalSheets}</div><div class="lbl">Sheets</div></div>`;
  html += `<div class="summary-item"><div class="val">${pack.summary.generatedSheets}</div><div class="lbl">Generated</div></div>`;
  html += `<div class="summary-item"><div class="val">${pack.summary.missingDataSheets}</div><div class="lbl">Missing Data</div></div>`;
  html += `<div class="summary-item"><div class="val">${pack.summary.warnings}</div><div class="lbl">Warnings</div></div>`;
  html += `<div class="summary-item"><div class="val">${pack.summary.errors}</div><div class="lbl">Errors</div></div>`;
  html += `<div class="summary-item"><div class="val">${pack.summary.blockers}</div><div class="lbl">Blockers</div></div>`;
  html += `</div></div>`;

  // Each sheet
  pack.sheets.forEach(sheet => {
    html += renderSheetHtml(sheet);
  });

  html += `<div style="text-align:center;padding:20px;font-size:9px;color:#94a3b8;">Generated by Hardware Studio — ${new Date(pack.generatedAt).toISOString()}</div>`;
  html += `</body></html>`;
  return html;
}

// ---- Summary JSON Export ----
export function exportBlueprintPackSummaryJson(pack: BlueprintPack): string {
  const summary = {
    id: pack.id,
    projectName: pack.projectName,
    generatedAt: pack.generatedAt,
    revision: pack.revision,
    status: pack.status,
    summary: pack.summary,
    sheets: pack.sheets.map(s => ({
      sheetNo: s.sheetNo,
      title: s.title,
      category: s.category,
      status: s.status,
      warningCount: s.warnings.length,
      tableCount: s.tables.length,
      drawingObjectCount: s.drawing.objects.length,
    })),
  };
  return JSON.stringify(summary, null, 2);
}
