import type { DeviceKnowledgeEntry, KnowledgeProvenance } from './deviceKnowledge';

const OPEN_SOURCE_LIBRARY_REFERENCES = [
  {
    label: 'KiCad documentation — symbols, footprints, fields, and 3D models',
    url: 'https://docs.kicad.org/9.0/en/eeschema/eeschema.html',
  },
  {
    label: 'LibrePCB documentation — components, devices, packages, and pin mapping',
    url: 'https://librepcb.org/docs/quickstart/create-library-elements/',
  },
  {
    label: 'Zephyr documentation — typed hardware descriptions and bindings',
    url: 'https://docs.zephyrproject.org/latest/build/dts/bindings.html',
  },
];

const ARDUINO_LEARNING_REFERENCE = {
  label: 'Arduino documentation — beginner electronics examples',
  url: 'https://docs.arduino.cc/built-in-examples',
};

function provenance(summary: string): KnowledgeProvenance {
  return {
    qualification: 'generic-reviewed',
    reviewedOn: '2026-08-02',
    summary,
    references: [...OPEN_SOURCE_LIBRARY_REFERENCES, ARDUINO_LEARNING_REFERENCE],
  };
}

export const starterDeviceKnowledge: readonly DeviceKnowledgeEntry[] = [
  {
    id: 'microcontroller',
    category: 'Controllers',
    name: 'Microcontroller',
    commonNames: ['MCU', 'controller chip', 'embedded controller'],
    aliases: ['micro controller', 'processor board', 'control IC'],
    keywords: ['gpio', 'adc', 'pwm', 'uart', 'spi', 'i2c', 'firmware', 'clock', 'reset'],
    summary: 'A programmable integrated circuit that reads inputs, runs firmware, and controls outputs inside a product.',
    useCases: ['Reading buttons and sensors', 'Driving LEDs, displays, and motors', 'Running product state machines', 'Communicating with other devices'],
    whenToUse: ['The product needs programmable behavior', 'Several peripherals must be coordinated', 'Behavior will evolve through firmware'],
    whenNotToUse: ['A fixed analog or logic circuit is simpler and safer', 'The required timing or processing exceeds the selected MCU', 'The environment needs a certified controller not covered by the project'],
    prerequisites: {
      electrical: ['A verified power rail and decoupling plan', 'Clock and reset requirements from the selected datasheet', 'Logic-level compatibility for every connected device'],
      mechanical: ['Package and assembly process suitable for the PCB', 'Access to programming or debug pads/connectors'],
      firmware: ['A supported toolchain and target definition', 'Pin ownership and peripheral mappings', 'Boot, update, and recovery strategy'],
    },
    connection: {
      portsAndPins: ['Power and ground pins', 'Reset or enable', 'GPIO', 'ADC/DAC where available', 'UART, SPI, I2C, USB, SWD, or JTAG as supported'],
      protocols: ['GPIO', 'UART', 'SPI', 'I2C', 'PWM', 'ADC', 'USB', 'SWD', 'JTAG'],
      operatingEnvelope: ['Supply, current, clock, and temperature limits are manufacturer-part specific', 'Every I/O pin has voltage, current, and alternate-function limits'],
      orientationAndPolarity: ['Package pin 1 and exposed-pad orientation must match the footprint', 'Power and ground pins are not interchangeable'],
      steps: ['Choose the MCU from product requirements and peripheral needs', 'Verify package, supply, clock, reset, and programming requirements', 'Map each used signal to an exact pin and peripheral', 'Add required support parts from the reference design', 'Build a minimal firmware and bring-up test before adding full behavior'],
    },
    commonMistakes: ['Selecting by headline features without checking usable pins', 'Missing decoupling or exposed-pad connections', 'Using boot/debug pins without understanding startup behavior', 'Assuming all GPIOs tolerate the same voltage or current'],
    safetyNotes: ['Do not connect unknown-voltage signals directly to MCU pins', 'Treat radio, USB, battery, and mains-connected designs as specialist review areas'],
    validationSuggestions: ['Measure every power rail during startup', 'Verify reset and programming access', 'Run a pin-by-pin peripheral smoke test', 'Record firmware build and exact hardware revision'],
    relatedIds: ['voltage-regulator', 'debug-connector', 'i2c-sensor', 'display'],
    alternatives: ['Fixed-function logic', 'Programmable logic device', 'Application processor', 'Analog control circuit'],
    workbenches: [
      { viewId: 'component-library', label: 'Component Library', action: 'Select a qualified MCU definition and package.' },
      { viewId: 'pin-map', label: 'Pin Map', action: 'Assign exact product functions to MCU pins.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect power, reset, programming, and peripherals.' },
      { viewId: 'firmware-studio', label: 'Firmware Modules', action: 'Create the firmware responsibilities and drivers.' },
    ],
    nextActions: ['List required peripherals and pin count', 'Select a specific manufacturer part', 'Open its datasheet and reference design', 'Create a minimal bring-up checklist'],
    provenance: provenance('Generic controller guidance reviewed against open-source ECAD library and hardware-description patterns.'),
  },
  {
    id: 'voltage-regulator',
    category: 'Power',
    name: 'Voltage Regulator',
    commonNames: ['regulator', 'LDO', 'buck converter', 'boost converter'],
    aliases: ['power converter', 'DC-DC', 'supply regulator'],
    keywords: ['vin', 'vout', 'enable', 'feedback', 'efficiency', 'dropout', 'thermal'],
    summary: 'A power device that converts an input supply into a controlled voltage rail for the rest of the product.',
    useCases: ['Creating 3.3 V or other logic rails', 'Reducing battery voltage', 'Boosting a low source voltage', 'Sequencing or enabling subsystems'],
    whenToUse: ['Loads need a voltage different from the source', 'Supply variation must be controlled', 'Power domains need independent enable or filtering'],
    whenNotToUse: ['The source already meets every load requirement with adequate margin', 'Losses or heat exceed the enclosure capability', 'A selected topology cannot handle transient or peak demand'],
    prerequisites: {
      electrical: ['Known input range and worst-case load current', 'Stable capacitor values and types from the datasheet', 'Thermal and efficiency estimate'],
      mechanical: ['Copper area, airflow, and package thermal path', 'Inductor and switching-loop placement for switch-mode parts'],
      firmware: ['Enable sequencing or power-good handling when software controlled'],
    },
    connection: {
      portsAndPins: ['VIN', 'VOUT', 'GND', 'EN', 'FB or sense', 'Power-good where provided'],
      protocols: ['Power rail', 'Enable GPIO', 'Power-good GPIO'],
      operatingEnvelope: ['Input, output, load, dropout, switching frequency, and thermal limits are part-specific'],
      orientationAndPolarity: ['Input and output capacitors can be polarized', 'Pin 1 and exposed thermal pad must match the package'],
      steps: ['Define source and load envelopes', 'Choose linear or switching topology intentionally', 'Copy the manufacturer reference circuit first', 'Place the critical loop and capacitors according to layout guidance', 'Measure startup, ripple, load step, and temperature'],
    },
    commonMistakes: ['Ignoring peak current or dropout', 'Using the wrong capacitor ESR or value', 'Long switching-current loops', 'Calling a rail verified without load and thermal tests'],
    safetyNotes: ['A regulator does not automatically provide battery protection, isolation, or overcurrent safety', 'High voltage and high power require qualified review'],
    validationSuggestions: ['No-load and full-load voltage', 'Startup and shutdown waveform', 'Ripple and transient response', 'Thermal measurement in the real enclosure'],
    relatedIds: ['battery', 'capacitor', 'protection-device', 'microcontroller'],
    alternatives: ['Direct battery rail', 'Pre-regulated external supply', 'Isolated converter', 'Dedicated power-management IC'],
    workbenches: [
      { viewId: 'power-tree', label: 'Power Tree', action: 'Define the source, rail, loads, duty cycles, and margins.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Build the reviewed reference circuit.' },
      { viewId: 'board-designer', label: 'Board Designer', action: 'Place the critical power loop and thermal copper.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Plan ripple, load, and temperature tests.' },
    ],
    nextActions: ['Calculate worst-case current', 'Select topology', 'Verify the reference design', 'Define measurable rail acceptance limits'],
    provenance: provenance('Generic power-conversion guidance; exact values must come from the selected regulator datasheet and reference layout.'),
  },
  {
    id: 'battery',
    category: 'Power',
    name: 'Battery',
    commonNames: ['cell', 'battery pack', 'rechargeable battery'],
    aliases: ['Li-ion cell', 'LiPo', 'primary cell', 'energy source'],
    keywords: ['capacity', 'mah', 'charge', 'discharge', 'protection', 'fuel gauge', 'connector'],
    summary: 'An electrochemical energy source whose chemistry, protection, charging, mechanical containment, and lifecycle must be designed together.',
    useCases: ['Portable products', 'Backup power', 'Wearables', 'Remote sensing'],
    whenToUse: ['The product must operate without continuous external power', 'Runtime and recharge behavior are explicit requirements'],
    whenNotToUse: ['The enclosure cannot safely contain the selected cell', 'Charging, protection, shipping, or certification cannot be handled', 'External power is simpler and acceptable'],
    prerequisites: {
      electrical: ['Chemistry-specific charger and protection', 'Known peak and continuous load', 'Connector, fuse, sensing, and cutoff strategy'],
      mechanical: ['Cell swelling and tolerance allowance', 'Retention without puncture or crushing', 'Thermal and service strategy'],
      firmware: ['State-of-charge reporting and low-battery behavior where required'],
    },
    connection: {
      portsAndPins: ['Positive terminal', 'Negative terminal', 'Temperature or identification pins on some packs'],
      protocols: ['Power', 'Thermistor', 'Fuel-gauge I2C or one-wire on some packs'],
      operatingEnvelope: ['Voltage, charge rate, discharge rate, temperature, capacity, and cutoff are chemistry- and cell-specific'],
      orientationAndPolarity: ['Polarity is mandatory', 'Connector keying and wire colors are not sufficient verification by themselves'],
      steps: ['Choose chemistry from product, safety, and lifecycle needs', 'Select a real cell with traceable documentation', 'Design protection and charging around that exact cell', 'Verify mechanical retention and clearances', 'Test runtime, cutoff, charge, temperature, and fault behavior'],
    },
    commonMistakes: ['Using nominal capacity as guaranteed runtime', 'Missing peak-current voltage sag', 'Treating a charger as complete protection', 'Ignoring connector reversal or cell swelling'],
    safetyNotes: ['Never short, puncture, crush, overcharge, or charge an unsupported cell', 'Battery-powered products require chemistry-appropriate safety, transport, and regulatory review'],
    validationSuggestions: ['Runtime across operating modes', 'Peak-load voltage sag', 'Charge and cutoff behavior', 'Temperature and enclosure inspection', 'Fault and reversed-connection review'],
    relatedIds: ['voltage-regulator', 'protection-device', 'usb-c-connector'],
    alternatives: ['External DC supply', 'USB power only', 'Primary battery', 'Supercapacitor for short backup'],
    workbenches: [
      { viewId: 'power-tree', label: 'Power Tree', action: 'Model capacity, current, modes, and runtime assumptions.' },
      { viewId: 'mechanical-studio', label: 'Mechanical Studio', action: 'Reserve the real cell envelope, retention, and swelling clearance.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Plan runtime, charging, temperature, and fault checks.' },
      { viewId: 'bom', label: 'Bill of Materials', action: 'Record the exact qualified cell and approved alternatives.' },
    ],
    nextActions: ['Choose chemistry and form factor', 'Obtain the exact cell datasheet', 'Create the power and mechanical safety checklist', 'Define runtime and charging tests'],
    provenance: provenance('Generic battery-system guidance only; the exact cell, charger, protection, enclosure, and compliance requirements remain authoritative.'),
  },
  {
    id: 'usb-c-connector',
    category: 'Interfaces',
    name: 'USB-C Connector',
    commonNames: ['USB Type-C receptacle', 'Type-C port'],
    aliases: ['USB-C socket', 'USB C connector'],
    keywords: ['cc1', 'cc2', 'vbus', 'd+', 'd-', 'shield', 'esd', 'power delivery'],
    summary: 'A reversible connector that can carry power and data, but requires the correct configuration, protection, routing, and mechanical support.',
    useCases: ['Power input', 'USB data', 'Firmware update', 'Charging'],
    whenToUse: ['A modern reversible external connector is needed', 'USB power or data requirements are defined'],
    whenNotToUse: ['The design cannot implement required USB-C configuration and protection', 'A simpler keyed connector better fits the environment'],
    prerequisites: {
      electrical: ['Correct CC configuration for source or sink role', 'VBUS protection and current plan', 'ESD protection and controlled data routing when data is used'],
      mechanical: ['Connector cutout, insertion forces, shell anchoring, and keepouts'],
      firmware: ['USB stack, bootloader, or power-role behavior when applicable'],
    },
    connection: {
      portsAndPins: ['VBUS', 'GND', 'CC1', 'CC2', 'D+', 'D-', 'Shield', 'SuperSpeed pairs where supported'],
      protocols: ['USB 2.0', 'USB 3.x', 'USB Power Delivery', 'Power-only Type-C'],
      operatingEnvelope: ['Current and voltage capability depend on role, configuration, cable, controller, and negotiated mode'],
      orientationAndPolarity: ['The receptacle is reversible but each footprint pad must map correctly', 'Shield and chassis strategy must be intentional'],
      steps: ['Define power-only or data role', 'Choose a connector with verified footprint and mechanical drawing', 'Implement CC and protection from the applicable reference design', 'Route data pairs and shield according to the required USB generation', 'Validate both plug orientations and representative cables'],
    },
    commonMistakes: ['Leaving CC pins unconfigured', 'Assuming a connector alone enables Power Delivery', 'Weak mechanical anchoring', 'Routing data pairs without impedance and return-path control'],
    safetyNotes: ['Do not advertise or draw more power than the implemented role supports', 'External ports need fault, ESD, and enclosure review'],
    validationSuggestions: ['Plug orientation test', 'Cable compatibility matrix', 'Power-current and voltage-drop test', 'USB enumeration and transfer test', 'Mechanical insertion-cycle inspection'],
    relatedIds: ['battery', 'voltage-regulator', 'protection-device', 'debug-connector'],
    alternatives: ['Micro-USB', 'Barrel connector', 'Magnetic pogo connector', 'Dedicated programming header'],
    workbenches: [
      { viewId: 'component-library', label: 'Component Library', action: 'Select a connector with a verified footprint and mechanical drawing.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Add CC configuration, ESD, power, and data connections.' },
      { viewId: 'board-designer', label: 'Board Designer', action: 'Route pairs and anchor the shell with the real edge geometry.' },
      { viewId: 'mechanical-studio', label: 'Mechanical Studio', action: 'Create the enclosure opening and insertion clearance.' },
    ],
    nextActions: ['Decide power-only or data role', 'Select exact connector', 'Add the reference circuit', 'Define cable and orientation tests'],
    provenance: provenance('Generic USB-C concept and workflow guidance; exact role, current, routing, and compliance come from the selected implementation and USB specifications.'),
  },
  {
    id: 'push-button',
    category: 'Inputs',
    name: 'Push Button',
    commonNames: ['momentary switch', 'tactile switch', 'user button'],
    aliases: ['pushbutton', 'switch input', 'tact switch'],
    keywords: ['gpio', 'pull-up', 'pull-down', 'debounce', 'normally open', 'normally closed'],
    summary: 'A mechanical input that changes an electrical contact state when pressed and usually needs biasing and debounce handling.',
    useCases: ['User input', 'Reset', 'Power control', 'Mode selection'],
    whenToUse: ['A clear physical action is required', 'The environment and lifetime fit a mechanical switch'],
    whenNotToUse: ['Sealing, lifetime, size, or accidental activation makes a mechanical button unsuitable'],
    prerequisites: {
      electrical: ['Pull-up or pull-down strategy', 'Voltage compatibility', 'Protection for exposed or long wiring'],
      mechanical: ['Actuator travel, force, cap, opening, alignment, and lifecycle'],
      firmware: ['Debounce, long-press, repeat, and wake behavior as required'],
    },
    connection: {
      portsAndPins: ['Common', 'Normally open', 'Normally closed on some switches'],
      protocols: ['GPIO', 'Interrupt or wake input'],
      operatingEnvelope: ['Contact voltage, current, bounce, lifetime, and force are switch-specific'],
      orientationAndPolarity: ['Most simple contacts are non-polarized, but multi-pin tactile switches often duplicate contacts internally'],
      steps: ['Choose normally-open or normally-closed behavior', 'Verify the switch pin topology', 'Add biasing and protection', 'Define mechanical alignment', 'Implement and test debounce and user interaction timing'],
    },
    commonMistakes: ['Connecting two internally common pins as if they were separate contacts', 'Floating GPIO input', 'No debounce', 'Enclosure force applied off-axis'],
    safetyNotes: ['Do not use a low-rated signal switch to interrupt unsafe power', 'Emergency or safety controls require appropriate rated hardware and architecture'],
    validationSuggestions: ['Electrical state in released and pressed conditions', 'Debounce timing', 'Repeated press and long-press behavior', 'Mechanical alignment and cycle test'],
    relatedIds: ['microcontroller', 'resistor', 'protection-device'],
    alternatives: ['Capacitive touch', 'Hall sensor', 'Rotary encoder', 'Sealed membrane switch'],
    workbenches: [
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect the contact, bias resistor, and protection.' },
      { viewId: 'pin-map', label: 'Pin Map', action: 'Assign the input to a suitable GPIO or wake pin.' },
      { viewId: 'mechanical-studio', label: 'Mechanical Studio', action: 'Align the actuator, cap, and enclosure opening.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Test debounce, press timing, and lifecycle behavior.' },
    ],
    nextActions: ['Inspect the switch contact diagram', 'Choose biasing', 'Map the GPIO', 'Define press and debounce acceptance behavior'],
    provenance: provenance('Generic switch input guidance based on beginner electronics and structured component-library practice.'),
  },
  {
    id: 'led',
    category: 'Outputs',
    name: 'LED Indicator',
    commonNames: ['light-emitting diode', 'status LED', 'indicator light'],
    aliases: ['LED', 'indicator diode'],
    keywords: ['anode', 'cathode', 'current limiting', 'gpio', 'pwm', 'brightness'],
    summary: 'A polarized semiconductor light source commonly used for status, feedback, illumination, or optical signaling.',
    useCases: ['Status indication', 'User feedback', 'Backlight', 'Optical signaling'],
    whenToUse: ['A visible low-cost output is appropriate', 'Brightness, color, viewing angle, and power are defined'],
    whenNotToUse: ['The environment or accessibility requirements need another feedback channel', 'The controller cannot safely drive the required current directly'],
    prerequisites: {
      electrical: ['Current-limiting method', 'Forward-voltage and current information for the exact LED', 'Driver transistor or IC for higher current'],
      mechanical: ['Viewing angle, light pipe, diffuser, opening, and assembly orientation'],
      firmware: ['Active-high or active-low logic', 'PWM or animation behavior where used'],
    },
    connection: {
      portsAndPins: ['Anode', 'Cathode', 'Multiple color channels on RGB devices'],
      protocols: ['GPIO', 'PWM', 'Serial LED protocols for addressable devices'],
      operatingEnvelope: ['Forward voltage, current, power, brightness, and temperature are LED-specific'],
      orientationAndPolarity: ['Anode and cathode must be identified in symbol, footprint, package marking, and assembly documentation'],
      steps: ['Choose color, brightness, and viewing arrangement', 'Calculate or select current limiting from verified values', 'Decide direct GPIO or driver', 'Align package and enclosure optics', 'Measure current and visible behavior across supply range'],
    },
    commonMistakes: ['No current-limiting resistor or driver', 'Reversed polarity', 'Exceeding GPIO current', 'Choosing brightness without enclosure and ambient-light testing'],
    safetyNotes: ['High-power, ultraviolet, infrared, or laser-class emitters need specialist safety review'],
    validationSuggestions: ['Current and voltage measurement', 'Polarity and assembly inspection', 'Brightness across supply and ambient conditions', 'Firmware state and PWM test'],
    relatedIds: ['resistor', 'microcontroller', 'protection-device'],
    alternatives: ['Display', 'Buzzer', 'Haptic actuator', 'Mechanical indicator'],
    workbenches: [
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Add the LED, current limiting, and driver if needed.' },
      { viewId: 'pin-map', label: 'Pin Map', action: 'Assign the GPIO or PWM output.' },
      { viewId: 'mechanical-studio', label: 'Mechanical Studio', action: 'Define the light path, diffuser, and viewing angle.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Verify current, brightness, and state behavior.' },
    ],
    nextActions: ['Choose exact LED', 'Determine current-limiting method', 'Check GPIO capability', 'Define visible acceptance tests'],
    provenance: provenance('Generic LED guidance; exact current, voltage, thermal, optical, and polarity data must come from the selected part.'),
  },
  {
    id: 'resistor',
    category: 'Passives',
    name: 'Resistor',
    commonNames: ['fixed resistor', 'pull-up resistor', 'current-limiting resistor'],
    aliases: ['R', 'resistive component'],
    keywords: ['ohm', 'tolerance', 'power rating', 'pull-up', 'divider', 'termination'],
    summary: 'A passive component that limits current, biases signals, divides voltage, terminates lines, or senses current.',
    useCases: ['LED current limiting', 'Pull-up and pull-down networks', 'Voltage dividers', 'Feedback and gain setting', 'Current sensing'],
    whenToUse: ['A known resistance is needed within power and tolerance limits'],
    whenNotToUse: ['A resistor would waste unacceptable power', 'The function needs active regulation, isolation, or nonlinear protection'],
    prerequisites: {
      electrical: ['Resistance, tolerance, power, voltage, noise, and temperature requirements'],
      mechanical: ['Package size and assembly method', 'Creepage or pulse spacing where relevant'],
      firmware: ['ADC scaling or calibration assumptions when part of a measurement path'],
    },
    connection: {
      portsAndPins: ['Two passive terminals'],
      protocols: [],
      operatingEnvelope: ['Resistance, tolerance, power, voltage, pulse, and temperature ratings are part-specific'],
      orientationAndPolarity: ['Ordinary resistors are non-polarized; resistor networks may have pin-specific internal connections'],
      steps: ['Calculate the required function', 'Check worst-case current, voltage, power, and tolerance', 'Choose package and technology', 'Place according to signal or thermal needs', 'Measure the resulting circuit behavior'],
    },
    commonMistakes: ['Checking nominal value but not power', 'Ignoring tolerance stack', 'Using a divider as a power supply', 'Incorrect unit entry such as kΩ versus Ω'],
    safetyNotes: ['High-voltage and high-power resistors require spacing, heat, and failure-mode review'],
    validationSuggestions: ['Resistance or assembled circuit measurement', 'Power and temperature estimate', 'Worst-case tolerance calculation', 'Signal integrity check for termination uses'],
    relatedIds: ['led', 'push-button', 'capacitor', 'voltage-regulator'],
    alternatives: ['Active current source', 'Digital potentiometer', 'Current-regulator diode', 'Ferrite bead for frequency-dependent impedance'],
    workbenches: [
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Place the resistor with value and functional context.' },
      { viewId: 'bom', label: 'Bill of Materials', action: 'Record value, tolerance, power, package, and approved alternatives.' },
      { viewId: 'board-designer', label: 'Board Designer', action: 'Place it near the node it controls or senses.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Verify the resulting current, voltage, or bias.' },
    ],
    nextActions: ['Calculate nominal value', 'Run worst-case power and tolerance checks', 'Select package', 'State the resistor purpose in the schematic'],
    provenance: provenance('Generic passive-component guidance; selected value, tolerance, package, and ratings remain project-specific.'),
  },
  {
    id: 'capacitor',
    category: 'Passives',
    name: 'Capacitor',
    commonNames: ['decoupling capacitor', 'bulk capacitor', 'filter capacitor'],
    aliases: ['C', 'bypass capacitor'],
    keywords: ['farad', 'decoupling', 'bypass', 'filter', 'esr', 'voltage rating', 'dielectric'],
    summary: 'A passive component that stores electric charge and is used for decoupling, filtering, timing, energy buffering, and signal coupling.',
    useCases: ['IC decoupling', 'Power-rail bulk storage', 'Filters', 'Timing networks', 'AC coupling'],
    whenToUse: ['A circuit or datasheet requires local energy storage or frequency-dependent impedance'],
    whenNotToUse: ['The chosen dielectric, voltage, ESR, leakage, or tolerance cannot satisfy the function'],
    prerequisites: {
      electrical: ['Capacitance, voltage, tolerance, dielectric, ESR, leakage, ripple, and bias behavior'],
      mechanical: ['Package size, height, polarity marking, and placement distance'],
      firmware: ['Startup timing implications when capacitors affect reset or enable'],
    },
    connection: {
      portsAndPins: ['Two terminals'],
      protocols: [],
      operatingEnvelope: ['Effective capacitance and rating depend on technology, voltage, frequency, and temperature'],
      orientationAndPolarity: ['Ceramic capacitors are usually non-polarized; electrolytic and tantalum types are polarized'],
      steps: ['Identify decoupling, bulk, filter, or timing purpose', 'Use the selected IC reference design as the starting point', 'Check effective capacitance and voltage margin', 'Place critical capacitors at the relevant pins or current loop', 'Measure startup, ripple, or frequency response'],
    },
    commonMistakes: ['Using nominal ceramic capacitance without DC-bias derating', 'Placing decoupling too far from the IC', 'Reversing a polarized capacitor', 'Ignoring inrush or discharge paths'],
    safetyNotes: ['Large or high-voltage capacitors can retain dangerous energy', 'Polarized capacitor failure can be hazardous'],
    validationSuggestions: ['Inspect placement and polarity', 'Measure rail ripple and startup', 'Check temperature and ripple current', 'Verify timing or filter response'],
    relatedIds: ['voltage-regulator', 'microcontroller', 'resistor', 'protection-device'],
    alternatives: ['RC network', 'LC filter', 'Supercapacitor', 'Active filter'],
    workbenches: [
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect the capacitor with its function and polarity.' },
      { viewId: 'board-designer', label: 'Board Designer', action: 'Place critical decoupling in the correct current loop.' },
      { viewId: 'bom', label: 'Bill of Materials', action: 'Record dielectric, voltage, tolerance, and package.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Measure ripple, startup, timing, or filter behavior.' },
    ],
    nextActions: ['Identify the capacitor function', 'Check effective value and rating', 'Place from the reference layout', 'Define a measurable validation method'],
    provenance: provenance('Generic capacitor guidance; exact dielectric and derating data must come from the selected part and circuit reference.'),
  },
  {
    id: 'environmental-sensor',
    category: 'Sensors',
    name: 'Temperature / Environmental Sensor',
    commonNames: ['temperature sensor', 'humidity sensor', 'environment sensor'],
    aliases: ['thermometer IC', 'temperature and humidity module'],
    keywords: ['temperature', 'humidity', 'pressure', 'accuracy', 'calibration', 'self-heating'],
    summary: 'A sensor that converts environmental conditions such as temperature, humidity, or pressure into electrical or digital measurements.',
    useCases: ['Environmental monitoring', 'Thermal protection', 'Comfort sensing', 'Compensation of other measurements'],
    whenToUse: ['The environment is a measurable product input', 'Accuracy, response time, placement, and calibration are defined'],
    whenNotToUse: ['The package cannot sample the intended environment', 'Required accuracy or range is not supported', 'Self-heating or enclosure lag dominates the reading'],
    prerequisites: {
      electrical: ['Compatible supply and interface', 'Required pull-ups, filtering, or analog conditioning'],
      mechanical: ['Airflow or thermal contact path', 'Isolation from heat sources and contamination as needed'],
      firmware: ['Driver, sampling cadence, conversion delay, filtering, and calibration handling'],
    },
    connection: {
      portsAndPins: ['Power', 'Ground', 'Digital bus or analog output', 'Interrupt or data-ready on some parts'],
      protocols: ['I2C', 'SPI', 'One-wire', 'Analog'],
      operatingEnvelope: ['Range, accuracy, response, humidity exposure, supply, and calibration are sensor-specific'],
      orientationAndPolarity: ['Some packages need an exposed sensing opening and must not be coated or obstructed'],
      steps: ['Define the measurand, range, accuracy, and response requirement', 'Select a sensor and interface', 'Design placement around the real environment', 'Implement driver and error handling', 'Compare readings against a traceable reference under representative conditions'],
    },
    commonMistakes: ['Placing next to a regulator or MCU heat source', 'Blocking the sensing port', 'Confusing resolution with accuracy', 'Ignoring startup and conversion timing'],
    safetyNotes: ['Do not use an unqualified general sensor as the sole protection for hazardous temperature or atmosphere'],
    validationSuggestions: ['Multi-point comparison against a reference', 'Response-time test', 'Self-heating and enclosure-lag test', 'Communication fault and out-of-range handling'],
    relatedIds: ['i2c-sensor', 'microcontroller', 'voltage-regulator'],
    alternatives: ['Thermistor', 'RTD', 'Thermocouple', 'Analog humidity sensor'],
    workbenches: [
      { viewId: 'component-library', label: 'Component Library', action: 'Select the exact sensor, package, and interface.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect supply, bus, pull-ups, and interrupt.' },
      { viewId: 'mechanical-studio', label: 'Mechanical Studio', action: 'Design the environmental or thermal path.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Create accuracy, response, and fault tests.' },
    ],
    nextActions: ['Write range and accuracy requirements', 'Choose sensing location', 'Select exact part', 'Plan comparison against a reference instrument'],
    provenance: provenance('Generic environmental-sensing guidance; exact accuracy, calibration, exposure, and placement limits are manufacturer-specific.'),
  },
  {
    id: 'i2c-sensor',
    category: 'Sensors',
    name: 'I2C Sensor',
    commonNames: ['I²C peripheral', 'two-wire sensor', 'digital sensor module'],
    aliases: ['IIC sensor', 'TWI sensor'],
    keywords: ['sda', 'scl', 'address', 'pull-up', 'bus', 'clock stretching', 'interrupt'],
    summary: 'A digital sensor connected through the shared two-wire I2C bus using clock, data, power, ground, and a device address.',
    useCases: ['Connecting several low-speed sensors', 'Reducing MCU pin count', 'Board-level digital measurement'],
    whenToUse: ['Bus speed and distance are suitable', 'Addresses do not conflict', 'The controller and voltage domain are compatible'],
    whenNotToUse: ['Long cables or noisy environments exceed a board-level bus', 'Required bandwidth, latency, or determinism is too high'],
    prerequisites: {
      electrical: ['SDA and SCL pull-ups sized for voltage, bus capacitance, and speed', 'Compatible logic levels', 'Address and interrupt strategy'],
      mechanical: ['Short controlled board routing or a reviewed cable implementation'],
      firmware: ['Driver, address, bus timeout, recovery, and device identification'],
    },
    connection: {
      portsAndPins: ['VDD', 'GND', 'SDA', 'SCL', 'INT or DRDY where available', 'Address-select pins on some parts'],
      protocols: ['I2C'],
      operatingEnvelope: ['Bus voltage, speed, capacitance, address, timing, and pull-ups are system-specific'],
      orientationAndPolarity: ['Power polarity and package pin 1 matter; SDA and SCL are distinct'],
      steps: ['Choose the bus voltage and speed', 'Check the sensor address and alternate-address options', 'Calculate or verify pull-ups', 'Map SDA, SCL, interrupt, and power pins', 'Scan and identify the device, then test reads, timeouts, and recovery'],
    },
    commonMistakes: ['Missing or duplicated pull-ups', 'Address conflict', 'Using 5 V pull-ups on a 3.3 V-only device', 'No timeout when a device holds the bus'],
    safetyNotes: ['Board-level I2C is not automatically suitable for exposed, long, or hazardous wiring'],
    validationSuggestions: ['Address scan', 'Waveform rise-time inspection', 'Read/write and interrupt test', 'Missing-device and stuck-bus recovery test'],
    relatedIds: ['microcontroller', 'environmental-sensor', 'resistor', 'protection-device'],
    alternatives: ['SPI sensor', 'Analog sensor', 'UART device', 'Differential industrial bus'],
    workbenches: [
      { viewId: 'pin-map', label: 'Pin Map', action: 'Assign SDA, SCL, interrupt, and address-select pins.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect the shared bus, pull-ups, and power.' },
      { viewId: 'firmware-studio', label: 'Firmware Modules', action: 'Define driver, address, timeout, and recovery behavior.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Test timing, addressing, faults, and recovery.' },
    ],
    nextActions: ['Check address and voltage', 'Verify pull-ups', 'Map the bus pins', 'Define timeout and recovery tests'],
    provenance: provenance('Generic I2C integration guidance informed by typed bus metadata patterns; the selected sensor timing remains authoritative.'),
  },
  {
    id: 'motor-actuator',
    category: 'Outputs',
    name: 'Motor / Actuator',
    commonNames: ['DC motor', 'vibration motor', 'solenoid', 'actuator'],
    aliases: ['haptic motor', 'load actuator'],
    keywords: ['driver', 'flyback', 'pwm', 'stall current', 'inrush', 'mosfet', 'mechanical load'],
    summary: 'An electromechanical load that converts electrical energy into motion or force and normally needs a driver, protection, and mechanical integration.',
    useCases: ['Motion', 'Haptic feedback', 'Pumps and fans', 'Locks and latches'],
    whenToUse: ['The product requires controlled motion, force, vibration, or airflow'],
    whenNotToUse: ['The power, noise, heat, lifetime, or mechanical risk cannot be supported'],
    prerequisites: {
      electrical: ['Driver rated for startup or stall current', 'Flyback or transient protection for inductive loads', 'Adequate power source and grounding'],
      mechanical: ['Mounting, load, travel, vibration isolation, wear, and obstruction analysis'],
      firmware: ['PWM, current limit, timeout, position feedback, or fault handling as required'],
    },
    connection: {
      portsAndPins: ['Motor terminals or phases', 'Driver input and enable', 'Current sense', 'Position or fault feedback where available'],
      protocols: ['PWM', 'GPIO', 'Analog drive', 'I2C or SPI for smart drivers'],
      operatingEnvelope: ['Voltage, startup/stall current, duty cycle, force, speed, temperature, and lifetime are actuator-specific'],
      orientationAndPolarity: ['DC polarity can reverse direction; brushless and stepper phases must be mapped correctly'],
      steps: ['Define motion and load requirements', 'Measure or obtain worst-case current', 'Select a driver and protection network', 'Design mounting and motion envelope', 'Test no-load, loaded, blocked, and fault conditions'],
    },
    commonMistakes: ['Driving directly from an MCU pin', 'Sizing from running current but not stall current', 'Missing flyback path', 'No mechanical end-stop or timeout'],
    safetyNotes: ['Moving parts can pinch, cut, overheat, or start unexpectedly', 'High-current and safety-critical actuation need qualified review and independent protection'],
    validationSuggestions: ['Startup and stall current', 'Motion under worst-case load', 'Temperature and duty-cycle test', 'Blocked-motion and driver-fault behavior', 'Mechanical lifetime test'],
    relatedIds: ['microcontroller', 'voltage-regulator', 'protection-device'],
    alternatives: ['Piezo actuator', 'Servo', 'Pneumatic mechanism', 'Passive spring mechanism'],
    workbenches: [
      { viewId: 'power-tree', label: 'Power Tree', action: 'Include startup, stall, and duty-cycle load.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Add the driver, protection, and sensing.' },
      { viewId: 'mechanical-studio', label: 'Mechanical Studio', action: 'Design mounting, travel, clearances, and load path.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Test load, stall, thermal, fault, and lifetime behavior.' },
    ],
    nextActions: ['Define required force or motion', 'Obtain stall/startup current', 'Choose driver and protection', 'Create blocked-motion and thermal tests'],
    provenance: provenance('Generic actuator integration guidance; exact current, force, lifetime, and protection are selected-device and mechanism specific.'),
  },
  {
    id: 'display',
    category: 'Outputs',
    name: 'Display',
    commonNames: ['OLED', 'LCD', 'screen', 'display module'],
    aliases: ['visual display', 'panel'],
    keywords: ['pixels', 'resolution', 'spi', 'i2c', 'parallel', 'backlight', 'framebuffer'],
    summary: 'A visual output that combines an electrical interface, display controller, optical stack, mechanical opening, and firmware rendering behavior.',
    useCases: ['Text and graphics', 'Menus', 'Status dashboards', 'Prompts and measurements'],
    whenToUse: ['The product needs more information than indicators can communicate', 'Power, readability, interface bandwidth, and enclosure space are available'],
    whenNotToUse: ['A simpler LED or external interface meets the need', 'Ambient, temperature, lifetime, or power conditions do not fit the technology'],
    prerequisites: {
      electrical: ['Supply and logic compatibility', 'Backlight or panel-current budget', 'Interface timing and level shifting where required'],
      mechanical: ['Active area, bezel, viewing angle, cover, flex cable, and assembly tolerance'],
      firmware: ['Driver, initialization, framebuffer or drawing model, fonts, refresh, and fault handling'],
    },
    connection: {
      portsAndPins: ['Power and ground', 'SPI, I2C, parallel, MIPI, or other interface', 'Reset', 'Chip select', 'Data/command', 'Backlight control'],
      protocols: ['SPI', 'I2C', 'Parallel RGB', 'MIPI DSI', 'PWM backlight'],
      operatingEnvelope: ['Supply, interface timing, current, refresh, temperature, and optical limits are display-specific'],
      orientationAndPolarity: ['Connector and flex orientation are critical', 'Active area is different from module and glass outline'],
      steps: ['Define content, resolution, readability, and update rate', 'Select display technology and exact module', 'Budget interface and power', 'Design bezel, active-area alignment, and assembly', 'Build a rendering smoke test and validate optical performance'],
    },
    commonMistakes: ['Designing the opening from active area only', 'Missing reset or level shifting', 'Underestimating backlight current or framebuffer memory', 'No burn-in or lifetime consideration for the technology'],
    safetyNotes: ['Glass, flex cables, and backlights require mechanical and electrical handling appropriate to the module'],
    validationSuggestions: ['Initialization and full-pattern test', 'Readability across viewing and ambient conditions', 'Power and temperature test', 'Pixel, color, refresh, and sleep/wake behavior'],
    relatedIds: ['microcontroller', 'voltage-regulator', 'usb-c-connector'],
    alternatives: ['LED indicators', 'E-paper', 'External phone/web interface', 'Audio or haptic feedback'],
    workbenches: [
      { viewId: 'component-library', label: 'Component Library', action: 'Select the exact controller, connector, and module geometry.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect interface, power, reset, and backlight.' },
      { viewId: 'mechanical-studio', label: 'Mechanical Studio', action: 'Align the active area, bezel, cover, and flex.' },
      { viewId: 'firmware-studio', label: 'Firmware Modules', action: 'Implement initialization, drawing, and power states.' },
    ],
    nextActions: ['Define content and viewing requirements', 'Choose exact display', 'Confirm interface and memory budget', 'Create mechanical and rendering tests'],
    provenance: provenance('Generic display integration guidance; exact optical, electrical, timing, and mechanical data come from the selected module.'),
  },
  {
    id: 'debug-connector',
    category: 'Debug',
    name: 'Programming / Debug Connector',
    commonNames: ['SWD header', 'JTAG header', 'ICSP header', 'programming pads'],
    aliases: ['debug port', 'programming connector', 'pogo pads'],
    keywords: ['swdio', 'swclk', 'jtag', 'reset', 'uart', 'programming', 'test pads'],
    summary: 'A controlled electrical and mechanical access point used to program firmware, recover devices, debug hardware, or support manufacturing test.',
    useCases: ['Initial programming', 'Firmware recovery', 'Interactive debugging', 'Factory test and logging'],
    whenToUse: ['The controller needs reliable development or production access', 'Recovery must remain possible after assembly'],
    whenNotToUse: ['A security policy forbids exposed access without a controlled alternative', 'The connector cannot be mechanically or electrically protected'],
    prerequisites: {
      electrical: ['Exact target debug signals, reference voltage, ground, reset, and protection', 'Compatible programmer and voltage domain'],
      mechanical: ['Connector or pogo geometry, keying, fixture access, strain, and enclosure service path'],
      firmware: ['Boot/debug policy, lock-state plan, recovery image, and production programming procedure'],
    },
    connection: {
      portsAndPins: ['Ground', 'Reference voltage', 'Clock', 'Data', 'Reset', 'Optional UART or power'],
      protocols: ['SWD', 'JTAG', 'ICSP', 'UART', 'USB bootloader'],
      operatingEnvelope: ['Signal voltage, connector pinout, speed, and target powering rules are target-specific'],
      orientationAndPolarity: ['Pin 1, keying, cable orientation, and target-voltage direction must be explicit'],
      steps: ['Choose the target protocol and programmer', 'Use a documented connector or fixture pinout', 'Add ground and reference voltage deliberately', 'Reserve mechanical access through development and production', 'Test program, erase, recover, and debug workflows'],
    },
    commonMistakes: ['No ground reference', 'Reversed cable', 'Programmer powering an incompatible target', 'Removing access before recovery and factory test are proven'],
    safetyNotes: ['Debug access can bypass normal product behavior and security', 'Never connect an unknown-voltage programmer or target'],
    validationSuggestions: ['Read target identity', 'Program and verify image', 'Reset and recover a blank or corrupted device', 'Fixture alignment and cycle test', 'Security-lock procedure review'],
    relatedIds: ['microcontroller', 'usb-c-connector', 'protection-device'],
    alternatives: ['USB bootloader', 'Wireless update', 'Tag-Connect style cable', 'Permanent header', 'Pogo fixture'],
    workbenches: [
      { viewId: 'pin-map', label: 'Pin Map', action: 'Reserve exact debug pins and their alternate functions.' },
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect target voltage, ground, clock, data, and reset.' },
      { viewId: 'board-designer', label: 'Board Designer', action: 'Place the connector or pogo pattern with fixture clearance.' },
      { viewId: 'firmware-studio', label: 'Firmware Modules', action: 'Document build, programming, boot, and recovery behavior.' },
    ],
    nextActions: ['Select protocol and programmer', 'Freeze connector pinout', 'Reserve physical access', 'Test blank-device programming and recovery'],
    provenance: provenance('Generic programming/debug access guidance; the selected target and programmer documentation define the exact pinout and electrical rules.'),
  },
  {
    id: 'protection-device',
    category: 'Power',
    name: 'Protection Device',
    commonNames: ['ESD diode', 'TVS diode', 'fuse', 'reverse-polarity protection'],
    aliases: ['surge protector', 'transient suppressor', 'protection circuit'],
    keywords: ['esd', 'tvs', 'fuse', 'overcurrent', 'reverse polarity', 'surge', 'clamp'],
    summary: 'A device or circuit intended to limit damage from abnormal voltage, current, polarity, electrostatic discharge, or external transients.',
    useCases: ['External connector protection', 'Battery and power-input protection', 'Inductive-load flyback', 'Overcurrent interruption'],
    whenToUse: ['A credible fault or external transient exists', 'The product safety and reliability analysis requires a defined response'],
    whenNotToUse: ['The selected part cannot survive or safely handle the real fault energy', 'Protection is being used to hide an undefined interface or grounding strategy'],
    prerequisites: {
      electrical: ['Threat or fault definition', 'Clamping, current, energy, speed, leakage, capacitance, and failure-mode requirements'],
      mechanical: ['Short current path and suitable thermal or clearance design'],
      firmware: ['Fault reporting, shutdown, or retry policy where electronically controlled'],
    },
    connection: {
      portsAndPins: ['Line and ground/reference for shunt protection', 'Series input/output for fuses and switches', 'Gate/control for active protection'],
      protocols: ['Power', 'Signal protection', 'Fault GPIO on active devices'],
      operatingEnvelope: ['Working voltage, clamp behavior, current, energy, speed, capacitance, and temperature are part-specific'],
      orientationAndPolarity: ['Many diodes and active protection parts are polarized', 'Ground or chassis return placement determines effectiveness'],
      steps: ['Define the fault or transient', 'Choose protection topology', 'Verify normal-operation impact', 'Place it at the entry or fault-current path', 'Test or review against the defined event and failure mode'],
    },
    commonMistakes: ['Selecting only by working voltage', 'Long trace between connector and ESD device', 'No return path', 'Assuming one device covers surge, ESD, overcurrent, and reverse polarity'],
    safetyNotes: ['Protection for mains, high energy, batteries, medical, automotive, or life-safety systems requires qualified engineering and applicable standards'],
    validationSuggestions: ['Continuity and polarity inspection', 'Normal leakage and signal-integrity check', 'Defined transient or fault test using suitable equipment', 'Post-event functional and thermal inspection'],
    relatedIds: ['usb-c-connector', 'battery', 'voltage-regulator', 'motor-actuator'],
    alternatives: ['Mechanical fuse', 'Resettable fuse', 'Active eFuse', 'Isolation', 'Connector keying and system-level prevention'],
    workbenches: [
      { viewId: 'schematic-editor', label: 'Schematic Editor', action: 'Connect protection to the defined interface and return path.' },
      { viewId: 'board-designer', label: 'Board Designer', action: 'Place protection at the entry and minimize the transient loop.' },
      { viewId: 'validation-studio', label: 'Validation Studio', action: 'Define normal-operation and fault-event checks.' },
      { viewId: 'bom', label: 'Bill of Materials', action: 'Record exact ratings, technology, and approved substitutions.' },
    ],
    nextActions: ['Name the fault or threat', 'Calculate normal and abnormal envelopes', 'Select topology and exact part', 'Define validation and safe failure behavior'],
    provenance: provenance('Generic protection-system guidance; exact transient, energy, safety, and compliance design requires part- and application-specific engineering.'),
  },
] as const;

export function getStarterKnowledgeEntry(entryId: string | undefined): DeviceKnowledgeEntry | undefined {
  if (!entryId) return undefined;
  return starterDeviceKnowledge.find((entry) => entry.id === entryId);
}
