import { FirmwareModule, FirmwareState, FirmwareTransition } from '../../types';
import { sanitizeCIdentifier } from './firmwareValidation';

export type TargetRTOS = 'BareMetal' | 'FreeRTOS' | 'Zephyr';

/** Generate C/C++ source code from firmware state machine definitions */
export function generateFirmwareSource(
  modules: FirmwareModule[],
  states: FirmwareState[],
  transitions: FirmwareTransition[],
  targetRtos: TargetRTOS = 'FreeRTOS'
): { headerContent: string; sourceContent: string } {
  const lines_h: string[] = [];
  const lines_c: string[] = [];

  // Header file
  lines_h.push('#ifndef FIRMWARE_GENERATED_H');
  lines_h.push('#define FIRMWARE_GENERATED_H');
  lines_h.push('');
  lines_h.push('/* Auto-generated by Hardware Studio */');
  lines_h.push(`/* Target Architecture: ${targetRtos} */`);
  lines_h.push('');
  lines_h.push('#include <stdint.h>');
  lines_h.push('#include <stdbool.h>');
  if (targetRtos === 'FreeRTOS') {
    lines_h.push('#include "FreeRTOS.h"');
    lines_h.push('#include "task.h"');
    lines_h.push('#include "queue.h"');
  }
  lines_h.push('');

  // State enum
  if (states.length > 0) {
    lines_h.push('typedef enum {');
    for (let i = 0; i < states.length; i++) {
      const id = sanitizeCIdentifier(states[i].name);
      const comma = i < states.length - 1 ? ',' : '';
      lines_h.push(`    STATE_${id.toUpperCase()}${comma}`);
    }
    lines_h.push('} SystemState_t;');
    lines_h.push('');
  }

  // Module init/process prototypes
  for (const mod of modules) {
    const modId = sanitizeCIdentifier(mod.name);
    lines_h.push(`/* Module: ${mod.name} (${mod.type}) */`);
    lines_h.push(`void ${modId}_init(void);`);
    lines_h.push(`void ${modId}_process(void);`);
    lines_h.push('');
  }

  // State handlers
  if (states.length > 0) {
    lines_h.push('/* State handlers */');
    for (const state of states) {
      const stateId = sanitizeCIdentifier(state.name);
      lines_h.push(`void state_${stateId.toLowerCase()}_enter(void);`);
      lines_h.push(`void state_${stateId.toLowerCase()}_exit(void);`);
      lines_h.push(`SystemState_t state_${stateId.toLowerCase()}_run(void);`);
    }
    lines_h.push('');
  }

  lines_h.push('/* Main state machine handler */');
  lines_h.push('void state_machine_init(void);');
  lines_h.push('void state_machine_run(void);');
  if (targetRtos === 'FreeRTOS') {
    lines_h.push('void vTaskStateMachine(void *pvParameters);');
  }
  lines_h.push('');
  lines_h.push('#endif /* FIRMWARE_GENERATED_H */');

  // Source file
  lines_c.push('#include "firmware_generated.h"');
  lines_c.push('');
  lines_c.push('static SystemState_t current_state;');
  lines_c.push('');

  // Module implementations
  for (const mod of modules) {
    const modId = sanitizeCIdentifier(mod.name);
    lines_c.push(`/* Module: ${mod.name} (${mod.type}) */`);
    if (mod.linkedComponentIds.length > 0) {
      lines_c.push(`/* Linked Components: ${mod.linkedComponentIds.length} */`);
    }
    lines_c.push(`void ${modId}_init(void) {`);
    lines_c.push('    /* Initialize hardware peripherals */');
    lines_c.push('}');
    lines_c.push('');
    lines_c.push(`void ${modId}_process(void) {`);
    lines_c.push('    /* Process module logic */');
    lines_c.push('}');
    lines_c.push('');
  }

  // State handler implementations
  for (const state of states) {
    const stateId = sanitizeCIdentifier(state.name);
    lines_c.push(`/* State: ${state.name} (${state.type}) */`);

    lines_c.push(`void state_${stateId.toLowerCase()}_enter(void) {`);
    for (const action of state.entryActions || []) {
      lines_c.push(`    /* Action: ${action} */`);
    }
    lines_c.push('}');
    lines_c.push('');

    lines_c.push(`void state_${stateId.toLowerCase()}_exit(void) {`);
    for (const action of state.exitActions || []) {
      lines_c.push(`    /* Action: ${action} */`);
    }
    lines_c.push('}');
    lines_c.push('');

    lines_c.push(`SystemState_t state_${stateId.toLowerCase()}_run(void) {`);
    lines_c.push('    /* Evaluate transition events and guard conditions */');
    const outgoing = transitions.filter(t => t.sourceStateId === state.id);
    for (const tr of outgoing) {
      const targetState = states.find(s => s.id === tr.targetStateId);
      if (targetState) {
        const targetId = sanitizeCIdentifier(targetState.name);
        const condStr = tr.condition ? ` && (${tr.condition})` : '';
        lines_c.push(`    if (event_check("${tr.event}")${condStr}) {`);
        lines_c.push(`        state_${stateId.toLowerCase()}_exit();`);
        if (tr.action) lines_c.push(`        /* ${tr.action} */`);
        lines_c.push(`        state_${targetId.toLowerCase()}_enter();`);
        lines_c.push(`        return STATE_${targetId.toUpperCase()};`);
        lines_c.push('    }');
      }
    }
    lines_c.push(`    return STATE_${stateId.toUpperCase()};`);
    lines_c.push('}');
    lines_c.push('');
  }

  // Main state machine init/run dispatchers
  lines_c.push('void state_machine_init(void) {');
  const initialState = states.find(s => s.type === 'Initial') || states[0];
  if (initialState) {
    const initId = sanitizeCIdentifier(initialState.name);
    lines_c.push(`    current_state = STATE_${initId.toUpperCase()};`);
    lines_c.push(`    state_${initId.toLowerCase()}_enter();`);
  }
  lines_c.push('}');
  lines_c.push('');

  lines_c.push('void state_machine_run(void) {');
  lines_c.push('    switch (current_state) {');
  for (const state of states) {
    const stateId = sanitizeCIdentifier(state.name);
    lines_c.push(`        case STATE_${stateId.toUpperCase()}:`);
    lines_c.push(`            current_state = state_${stateId.toLowerCase()}_run();`);
    lines_c.push('            break;');
  }
  lines_c.push('        default:');
  lines_c.push('            break;');
  lines_c.push('    }');
  lines_c.push('}');
  lines_c.push('');

  if (targetRtos === 'FreeRTOS') {
    lines_c.push('/* FreeRTOS Task Loop */');
    lines_c.push('void vTaskStateMachine(void *pvParameters) {');
    lines_c.push('    state_machine_init();');
    lines_c.push('    for (;;) {');
    lines_c.push('        state_machine_run();');
    lines_c.push('        vTaskDelay(pdMS_TO_TICKS(10));');
    lines_c.push('    }');
    lines_c.push('}');
    lines_c.push('');
  }

  return {
    headerContent: lines_h.join('\n'),
    sourceContent: lines_c.join('\n'),
  };
}
