import { FirmwareModule, FirmwareState, FirmwareTransition } from '../../types';
import { sanitizeCIdentifier } from './firmwareValidation';

/** Generate C/C++ source skeleton from firmware definitions */
export function generateFirmwareSource(
  modules: FirmwareModule[],
  states: FirmwareState[],
  transitions: FirmwareTransition[]
): { headerContent: string; sourceContent: string } {
  const lines_h: string[] = [];
  const lines_c: string[] = [];

  // Header file
  lines_h.push('#ifndef FIRMWARE_GENERATED_H');
  lines_h.push('#define FIRMWARE_GENERATED_H');
  lines_h.push('');
  lines_h.push('/* Auto-generated by Hardware Studio */');
  lines_h.push('/* Do not edit manually */');
  lines_h.push('');

  // State enum
  if (states.length > 0) {
    lines_h.push('typedef enum {');
    for (let i = 0; i < states.length; i++) {
      const id = sanitizeCIdentifier(states[i].name);
      const comma = i < states.length - 1 ? ',' : '';
      lines_h.push(`    STATE_${id.toUpperCase()}${comma}`);
    }
    lines_h.push('} SystemState_t;');
    lines_h.push('');
  }

  // Module init/process prototypes
  for (const mod of modules) {
    const modId = sanitizeCIdentifier(mod.name);
    lines_h.push(`/* Module: ${mod.name} (${mod.type}) */`);
    lines_h.push(`void ${modId}_init(void);`);
    lines_h.push(`void ${modId}_process(void);`);
    lines_h.push('');
  }

  // State handlers
  if (states.length > 0) {
    lines_h.push('/* State handlers */');
    for (const state of states) {
      const stateId = sanitizeCIdentifier(state.name);
      lines_h.push(`void state_${stateId.toLowerCase()}_enter(void);`);
      lines_h.push(`void state_${stateId.toLowerCase()}_exit(void);`);
      lines_h.push(`SystemState_t state_${stateId.toLowerCase()}_run(void);`);
    }
    lines_h.push('');
  }

  lines_h.push('/* Main state machine handler */');
  lines_h.push('void state_machine_init(void);');
  lines_h.push('void state_machine_run(void);');
  lines_h.push('');
  lines_h.push('#endif /* FIRMWARE_GENERATED_H */');

  // Source file
  lines_c.push('#include "firmware_generated.h"');
  lines_c.push('');
  lines_c.push('static SystemState_t current_state;');
  lines_c.push('');

  // Module implementations
  for (const mod of modules) {
    const modId = sanitizeCIdentifier(mod.name);
    lines_c.push(`/* Module: ${mod.name} (${mod.type}) */`);
    if (mod.linkedComponentIds.length > 0) {
      lines_c.push(`/* Hardware: ${mod.linkedComponentIds.length} linked component(s) */`);
    }
    lines_c.push(`void ${modId}_init(void) {`);
    lines_c.push('    /* TODO: Initialize hardware peripherals */');
    lines_c.push('}');
    lines_c.push('');
    lines_c.push(`void ${modId}_process(void) {`);
    lines_c.push('    /* TODO: Process module logic */');
    lines_c.push('}');
    lines_c.push('');
  }

  // State handler implementations
  for (const state of states) {
    const stateId = sanitizeCIdentifier(state.name);
    lines_c.push(`/* State: ${state.name} (${state.type}) */`);

    lines_c.push(`void state_${stateId.toLowerCase()}_enter(void) {`);
    for (const action of state.entryActions) {
      lines_c.push(`    /* Entry: ${action} */`);
    }
    lines_c.push('    /* TODO: Implement entry actions */');
    lines_c.push('}');
    lines_c.push('');

    lines_c.push(`void state_${stateId.toLowerCase()}_exit(void) {`);
    for (const action of state.exitActions) {
      lines_c.push(`    /* Exit: ${action} */`);
    }
    lines_c.push('    /* TODO: Implement exit actions */');
    lines_c.push('}');
    lines_c.push('');

    // Run function with transition logic
    const stateTransitions = transitions.filter(t => t.sourceStateId === state.id);
    lines_c.push(`SystemState_t state_${stateId.toLowerCase()}_run(void) {`);
    for (const t of stateTransitions) {
      const targetState = states.find(s => s.id === t.targetStateId);
      if (targetState) {
        const targetId = sanitizeCIdentifier(targetState.name);
        const condComment = t.condition ? ` && ${t.condition}` : '';
        lines_c.push(`    /* Event: ${t.event}${condComment} */`);
        if (t.action) {
          lines_c.push(`    /* Action: ${t.action} */`);
        }
        lines_c.push(`    /* TODO: Check event "${t.event}" and transition to STATE_${targetId.toUpperCase()} */`);
        lines_c.push('');
      }
    }
    lines_c.push(`    return STATE_${stateId.toUpperCase()};`);
    lines_c.push('}');
    lines_c.push('');
  }

  // State machine init/run
  const initialState = states.find(s => s.type === 'Initial');
  const initialId = initialState ? sanitizeCIdentifier(initialState.name) : (states.length > 0 ? sanitizeCIdentifier(states[0].name) : 'IDLE');

  lines_c.push('void state_machine_init(void) {');
  lines_c.push(`    current_state = STATE_${initialId.toUpperCase()};`);
  if (initialState) {
    lines_c.push(`    state_${initialId.toLowerCase()}_enter();`);
  }
  lines_c.push('}');
  lines_c.push('');

  lines_c.push('void state_machine_run(void) {');
  lines_c.push('    SystemState_t next_state = current_state;');
  lines_c.push('');
  lines_c.push('    switch (current_state) {');
  for (const state of states) {
    const stateId = sanitizeCIdentifier(state.name);
    lines_c.push(`        case STATE_${stateId.toUpperCase()}:`);
    lines_c.push(`            next_state = state_${stateId.toLowerCase()}_run();`);
    lines_c.push('            break;');
  }
  lines_c.push('        default:');
  lines_c.push('            break;');
  lines_c.push('    }');
  lines_c.push('');
  lines_c.push('    if (next_state != current_state) {');
  lines_c.push('        /* Exit current state */');
  lines_c.push('        switch (current_state) {');
  for (const state of states) {
    const stateId = sanitizeCIdentifier(state.name);
    lines_c.push(`            case STATE_${stateId.toUpperCase()}: state_${stateId.toLowerCase()}_exit(); break;`);
  }
  lines_c.push('            default: break;');
  lines_c.push('        }');
  lines_c.push('        /* Enter new state */');
  lines_c.push('        current_state = next_state;');
  lines_c.push('        switch (current_state) {');
  for (const state of states) {
    const stateId = sanitizeCIdentifier(state.name);
    lines_c.push(`            case STATE_${stateId.toUpperCase()}: state_${stateId.toLowerCase()}_enter(); break;`);
  }
  lines_c.push('            default: break;');
  lines_c.push('        }');
  lines_c.push('    }');
  lines_c.push('}');

  return {
    headerContent: lines_h.join('\n'),
    sourceContent: lines_c.join('\n')
  };
}
